[patch]
title = "EXE6 All-Stars Translated + BBN6 + KaizouLoader"
authors = [
    "luckytyphlosion <10688458+luckytyphlosion@users.noreply.github.com>",
    "Prof. 9 <prof9@outlook.com>",
    "ssbmars <46971717+ssbmars@users.noreply.github.com>",
    "exeguy11",
    "idealexe <omega_8810@yahoo.co.jp>"
]
source = "https://github.com/luckytyphlosion/bn6-all-stars"
license = "MIT (All-Stars + BBN6), UNLICENSED (Translation + KaizouLoader)"

[versions.'1.1.0']
netplay_compatibility = "exe6allstars_masters_v1.1.0"

[versions.'1.1.1']
netplay_compatibility = "exe6allstars_masters_v1.1.1"
