[patch]
title = "bn6_TwinLeaders"
authors = ["TTK ",
	"ChinaTV  <167204638+ChinaTV1@users.noreply.github.com>"]

[versions.'0.0.1']
netplay_compatibility = "bn6_tl1"

[versions.'0.0.2']
netplay_compatibility = "bn6_tl2"