[patch]
title = "Star Force Music Patch + BingusBN6"
authors = [
	"SaXor",
	"ssbmars <46971717+ssbmars@users.noreply.github.com>",
]
source = "https://github.com/ssbmars/BBN6"
license = "MIT"

[versions.'1.0.0']
netplay_compatibility = "bingusbn6v1"