[patch]
title = "EXE6 All-Stars + BBN6 + KaizouLoader + ORE SoundMod (TRANSLATION NEEDED)"
authors = [
    "luckytyphlosion <10688458+luckytyphlosion@users.noreply.github.com>",
    "Prof. 9 <prof9@outlook.com>",
    "ssbmars <46971717+ssbmars@users.noreply.github.com>",
    "idealexe <omega_8810@yahoo.co.jp>",
    "オレ{Ore} <oreo7863@gmail.com>"
]
source = "https://github.com/luckytyphlosion/bn6-all-stars"
license = "MIT (All-Stars + BBN6), UNLICENSED (KaizouLoader + ORE SoundMod)"

[versions.'1.1.0']
netplay_compatibility = "exe6allstars_masters_v1.1.0"
