[patch]
title = "BingusEXE6"
authors = ["ssbmars <46971717+ssbmars@users.noreply.github.com>"]
source = "https://github.com/ssbmars/BBN6"
license = "MIT"

[versions.'1.0.0']
netplay_compatibility = "bingusexe6v1"
[versions.'1.0.1']
netplay_compatibility = "bingusexe6v1"
