[patch]
title = "BA Star Force Black Ace Lock On"
authors = [
    "brianuuu <38166666+brianuuu@users.noreply.github.com>",
    "ahackerjack",
]

[versions.'10.0.0']
netplay_compatibility = "bn6_ba_lockon"
